# Shared prompt-diet byte-floor ledger (prompt-diet-floor-credit-drift /
# SPEC-DRAFT-spec-prompt-diet-floor-credit-drift.md).
#
# Single sourceable definition of the diet-floor constants, the
# JUSTIFIED_ADDITIONS ledger, and the two pure helpers, so
# tests/skills/test-aai-prompt-diet.sh and tests/skills/test-aai-verify-gate.sh
# can never drift from each other again (DEBT-0002 "two copies of one gate"
# pattern; docs/knowledge/LEARNED.md 2026-07-17).
#
# This file is a PURE library: no `set -u`, no `cd`, no test execution. It is
# only ever sourced, never run directly. bash-3.2 / Windows-Git-Bash safe: no
# `bc`, no `mapfile`, no `declare -A`.

# Byte baseline measured before any CHANGE-0011 edit (evidence:
# docs/ai/tdd/prompt-diet-kb-before.txt). AC floor: >= 28KB net reduction.
# BASELINE_PROMPT_BYTES and REQUIRED_REDUCTION_BYTES are the historical
# SPEC-0017 diet contract and stay UNCHANGED (DEBT-0002/SPEC-0048): rewriting
# them to match live measurements would erase history and IS the
# blank-raise anti-pattern the floor exists to prevent.
BASELINE_PROMPT_BYTES=357457
REQUIRED_REDUCTION_BYTES=28672   # 28 KB

# --- Justified-growth ledger (DEBT-0002/SPEC-0048 -> CHANGE-0040/SPEC-0059) -
# Canon-mandated prompt additions AFTER the SPEC-0017 diet legitimately grew
# the corpus. JUSTIFIED_GROWTH_BYTES is no longer a manually-bumped magic
# number: it is the portable bash-3.2 sum of the leading `<bytes>` field of
# each JUSTIFIED_ADDITIONS entry below (no bc, no mapfile, no declare -A --
# just `${_entry%% *}` + `$(( ))`, so it also runs under the Windows/Git-Bash
# matrix). Each entry is self-documenting: "<bytes> <ref> <rationale>".
# Adding a new legitimate prompt addition is a one-line array append with its
# own audit trail, not a recomputed constant (source: DEBT-0002 root cause,
# docs/knowledge/LEARNED.md 2026-07-17; true-up history: ISSUE-0016).
JUSTIFIED_ADDITIONS=(
  "6144 DEBT-0002 dual-verdict code-review taxonomy + VALIDATION 8a exception + CEREMONY LANE block (SPEC-0041) + RED_CLASS discipline (SPEC-0044) + SECRETS PREFLIGHT (SPEC-0045) + doc-number origin reservation (SPEC-0047) + ceremony-lane declaration surfaces (SPEC_TEMPLATE/PLANNING/WORKFLOW); measured deficit 5122 B, credit chosen 6144 B for 1022 B headroom"
  "1309 CHANGE-0037 deterministic close-ceremony wiring prose: SKILL_PR.prompt.md step 5c close-work-item.mjs invocation (+1144 B) + VALIDATION 8b hand-flip/hand-emit removal replaced by close-ceremony pointer (+165 B)"
  "1786 CHANGE-0038+0039 workflow-hardening wiring prose: METRICS_FLUSH.prompt.md rewrite (flush no longer emits close events, SPEC-0054) + SKILL_PR step 2b RECONCILE WORKTREE TELEMETRY invocation prose (SPEC-0055)"
  "3100 aai-release-skill new .aai/SKILL_RELEASE.prompt.md thin-wrapper prompt (SPEC-DRAFT-spec-aai-release-skill D9) documenting the /aai-release deterministic release-cut engine (--dry-run/--version/--confirm/--no-remote), mirroring SKILL_UPDATE.prompt.md's shape; measured deficit 3027 B, credit chosen 3100 B for 73 B headroom"
  "825 reaper-deterministic-age-guard SKILL_LOOP.prompt.md POST-TICK REAP + VALIDATION.prompt.md step-boundary reap prose documenting the step owner's AAI_REAP_STEP_START_EPOCH=\$(date +%s) capture/handoff to the reaper's deterministic epoch guard; measured deficit 825 B, credit chosen 825 B for 0 B headroom"
  "5396 hitl-decision-propagation SKILL_HITL.prompt.md STEP 4c trigger->target mapping table + normalization table + fail-closed rule + write-ordering rule (replacing the old absolute STATE-field prohibition) + ORCHESTRATION_HITL.prompt.md [HITL-<n>] blocking_reason stamping prose (SPEC-DRAFT-spec-hitl-decision-propagation); measured deficit 4848 B + 548 B code-review remediation (scope FAIL-CLOSED to enum targets so HITL-1..6/8 cannot deadlock; sanction set-human-input for the STEP 5 clear so the narrowed guardrail cannot forbid the resolver's own job); credit chosen 5396 B for 0 B headroom"
  "738 metrics-flush-strands-completed-refs METRICS_FLUSH.prompt.md RUN step 1 one-line --sweep mention (opt-in durable-provenance multi-ref flush of stranded work items, SPEC-DRAFT-spec-metrics-flush-sweep) + --events NO-OP caveat update; measured deficit 418 B initial + 320 B code-review reword, credit chosen 738 B for 0 B headroom"
  "494 branch-per-work-item-hygiene SKILL_PR.prompt.md '0. BRANCH HYGIENE' precondition (runs branch-guard.mjs, fail-closed, STOPS before push on a mis-branched scope) + AGENTS.md one-branch-per-work-item rule naming the guard (ISSUE-0024/SPEC-0070); measured deficit 494 B, credit chosen 494 B for 0 B headroom"
  "566 planning-companion-obligations PLANNING.prompt.md step 3a COMPANION OBLIGATIONS CHECK (closed two-entry planner checklist: prompt-corpus byte growth -> prompt-diet ledger true-up; new .aai/** file -> PROFILES.yaml classification), self-dogfooding the rule it introduces (SPEC-DRAFT-spec-planning-companion-obligations); measured deficit 566 B, credit chosen 566 B for 0 B headroom"
  "488 friction-shadow-capture-wiring AGENTS.md '### Friction capture (shadow)' thin inheriting pointer to the FRICTION_PROTOCOL.md 'Skill wiring (shadow capture)' seam (RFC-0012 Phase 1, SPEC-DRAFT-spec-friction-shadow-capture-wiring); AGENTS.md is prompt corpus per PLANNING step 3a but sits outside TEST-010's live .aai/*.prompt.md glob, so its 488 B growth carries no MEASURED deficit — credited manually at exactly the +488 B AGENTS.md delta (18425 -> 18913) to keep the corpus-as-defined reduction honest, headroom 0 -> 488 within the 2048 cap. The seam BODY lives in .aai/system/FRICTION_PROTOCOL.md (system/, not corpus, no ledger cost)"
  "1486 feedback-triage-offline new .aai/SKILL_FEEDBACK_TRIAGE.prompt.md thin wrapper (RFC-0012 Phase 2 / RFC-0013 Slice B, SPEC-DRAFT-spec-feedback-triage-offline) documenting the offline /aai-feedback-triage engine (spool -> gates -> v2-signal scoring -> fingerprint clustering -> local report, no network), mirroring SKILL_UPDATE's thin-wrapper shape; the 1486 B prompt is inside TEST-010's live .aai/*.prompt.md glob (measured deficit 998 B after consuming the prior 488 B headroom), credited at the true +1486 B growth so JUSTIFIED_GROWTH tracks the actual corpus addition, headroom back to 488 within the 2048 cap"
  "608 friction-feedback-discovery SKILL_WRAP_UP.prompt.md step 6 FRICTION FEEDBACK NUDGE (runs aai-feedback-status.mjs at session end to surface captured observations / pending --confirm drafts / gh auth state, silent when nothing captured; RFC-0012 discovery, SPEC-DRAFT-spec-friction-feedback-discovery); 608 B inside TEST-010's live .aai/*.prompt.md glob (measured deficit 120 B after the prior 488 B headroom), credited at the true +608 B growth, headroom back to 488 within the 2048 cap"
  "1931 feedback-upsert-review new .aai/SKILL_FEEDBACK_UPSERT.prompt.md thin wrapper (RFC-0012 Phase 2c / Slice C, SPEC-DRAFT-spec-feedback-upsert-review) documenting the review-mode /aai-feedback-upsert engine (prepare-only default; --publish <fp> --confirm the ONLY GitHub write; transmit-pass redaction reuse; v1:<fp> dedup marker; budget ledger; destination pin); the 1931 B prompt is inside TEST-010's live .aai/*.prompt.md glob (measured deficit 1443 B after consuming the prior 488 B headroom), credited at the true +1931 B growth, headroom back to 488 within the 2048 cap"
  "535 prune-stale-briefs SKILL_WRAP_UP.prompt.md step 6b STALE-BRIEF SWEEP (runs prune-stale-briefs.mjs at session end to prune terminal/orphan work-item briefs while KEEPING live handoffs, no-op when clean; AAI docs-lifecycle hygiene, CHANGE-DRAFT-prune-stale-briefs); the 535 B step is inside TEST-010's live .aai/*.prompt.md glob (measured deficit 47 B after consuming the prior 488 B headroom), credited at the true +535 B growth, headroom back to 488 within the 2048 cap"
  "3336 auditor-autonomy-pack new .aai/SKILL_SHIP.prompt.md end-to-end autopilot composition prompt (3201 B: need -> intake -> loop -> product docs -> ONE ship checkpoint -> PR, autopilot defaults recorded, never merges) + ORCHESTRATION.prompt.md / ORCHESTRATION_PARALLEL.prompt.md MODEL SELECTION suggested_model pointers to the .aai/system/MODEL_ROUTING.yaml deterministic tier->id binding (+15 B / +120 B; ORCHESTRATION held at 40 lines per the spec D5 cap); measured deficit 2848 B after consuming the prior 488 B headroom, credited at the true +3336 B growth, headroom back to 488 within the 2048 cap"
  "148 auditor-autonomy-pack AGENTS.md SKILL_SHIP listing line in the Universal Skills block — AGENTS.md sits outside TEST-010's live .aai/*.prompt.md glob, so the growth carries no MEASURED deficit; credited manually at the exact +148 B AGENTS.md delta (18913 -> 19061) to keep the corpus-as-defined reduction honest, headroom 488 -> 636 within the 2048 cap"
  "912 token-capture-canary SKILL_LOOP.prompt.md step 4 mandatory-usage-note reinforcement (usage_total_tokens=<N> non-optional at merge time) + step 6 MANDATORY --started/--harness wiring prose so log-tick's new duration/harness WARNINGs never fire on a correctly-wired tick (SPEC-DRAFT-spec-token-capture-canary Spec-AC-03); the edit is inside TEST-010's live .aai/*.prompt.md glob, measured growth 912 B (25941 -> 26853), credited 1:1 to keep headroom unchanged at 636 within the 2048 cap"
  "-3021 prompt-dedup-canonical-includes RECLAIMED credit (NEGATIVE entry, DEBT-0002/SPEC-0059 reconciliation): trimming PLANNING step 10's ceremony-level paraphrase to a WORKFLOW.md pointer + reducing VALIDATION's AC STATUS GATE Rules 1/2/4-format to a docs-audit.mjs --gate <ref> invocation (Rules 3/4-anti-cheat retained as prose, script does not compute them) + collapsing the D5 subagent-mode metrics/append-run boilerplate in PLANNING/IMPLEMENTATION/VALIDATION/REMEDIATION/SKILL_TDD to a pointer at the new .aai/ROLE_COMMON.md shrank the live .aai/*.prompt.md glob by a measured 4687 B (349697 -> 345010); .aai/ROLE_COMMON.md (1666 B) is added to TEST-010's extra accounting to neutralize the relocation, leaving a genuine 3021 B reduction (4687 minus 1666) that would otherwise push headroom from 636 to 3657, breaching HEADROOM_CAP=2048; this entry retires exactly that 3021 B of credit so headroom lands back at 636 within the cap (per TEST-010's own remediation message: the corpus legitimately shrank below the credit, so LOWER JUSTIFIED_GROWTH_BYTES)"
  "-9573 decapod-prune RECLAIMED credit (NEGATIVE entry, CHANGE-0077): deleting the dead .aai/SKILL_DECAPOD.prompt.md (9571 B file; retired 9573 B = 9571 B file + 2 B residual slack from the SPEC-0099 SKILL_CHECK_STATE reword credited at 286 but measuring 284; external decapod CLI never shipped, zero consumers since 2026-03 — skill-sweep group C evidence) shrank the live .aai/*.prompt.md glob accordingly; without reconciliation headroom jumps 636 -> 10209, breaching HEADROOM_CAP=2048; this entry retires exactly 9573 B of credit so headroom lands back at 636 within the cap (per TEST-010 remediation guidance: the corpus legitimately shrank below the credit, so LOWER JUSTIFIED_GROWTH_BYTES)"
  "992 pr-post-open-review-sweep SKILL_PR.prompt.md new step 5d POST-OPEN REVIEW SWEEP (operator-directed 2026-07-26): after gh pr create, poll bot inline comments post-CI (gh api pulls/<n>/comments + reviews); any findings route through the canonical EXTERNAL-REVIEW RESPONSE flow in SKILL_CODE_REVIEW.prompt.md (triage real/stale/duplicate/disputed, RED-proofed regression per real code finding, inline reply per thread — Codex P2 review on PR #160 replaced the original lighter duplicated triage path with this delegation, +97 B over the initial 895 B); wait for the CI re-run + one repeat sweep before any merge-readiness claim; merge boundary unchanged — promotes the PR #158/#159 review-response discipline (7+3 real bot findings fixed) from session memory to canon; measured deficit 356 B after consuming the prior 636 B headroom, credited at the true +992 B growth, headroom back to 636 within the 2048 cap"
  "32 subagent-protocol-slim SKILL_LOOP.prompt.md line-18 clause fix (code-review non-blocking finding disposition, review-20260726T184739Z): the AUTHORITATIVE SOURCES bullet no longer credits SUBAGENT_PROTOCOL.md with the result-block format (relocated to .aai/SUBAGENT_CONTRACT.md by CHANGE-0061) — reworded to name both files honestly; measured +32 B in the TEST-010 glob, credited at the true +32 B growth, headroom 636 -> 636 net across the CHANGE-0061 scope (all other edits byte-neutral renames)"
  "1881 friction-capture-default-on thin FRICTION HOOK pointers naming .aai/system/FRICTION_PROTOCOL.md's new 'Deterministic hook points' subsection (default-on best-effort capture at the moments AAI-owned friction is most salient, RFC-0012 root-cause finding): VALIDATION.prompt.md step 5h canon-file gate/lint/CI failure + step 8 validation-FAIL-recorded (+629 B), REMEDIATION.prompt.md step 1/2 remediation-dispatched (+288 B), SKILL_PR.prompt.md step 5d CI-check-failure-handled (+307 B), SKILL_WRAP_UP.prompt.md step 6 non-empty-spool triage + proposed-intake surfacing (+657 B) — the seam body itself lives in FRICTION_PROTOCOL.md (system/, not corpus, no ledger cost); measured deficit 1245 B after consuming the prior 636 B headroom, credited at the true +1881 B growth, headroom back to 636 within the 2048 cap"
  "453 friction-capture-default-on-r2 IMPLEMENTATION.prompt.md FRICTION HOOK (canon-surface check failure during implementation, default-on) — validation residual-risk R2 remediation: the ride's own motivating case (prompt-diet headroom-cap trap) fired during IMPLEMENTATION where no hook existed, so the class stayed uncaptured; thin pointer mirrors the VALIDATION 5h wording, swallow-and-never-mask contract unchanged; measured +453 B, credited at the true +453 B growth, headroom unchanged within the 2048 cap"
  "755 learned-append-gate SKILL_WRAP_UP.prompt.md step 3 PROPOSE NEW LEARNED RULES rewrite (confirmed rule now routes through a compact critic pass THEN the structural gate node .aai/scripts/learned-append.mjs --source/--text — never a direct edit) + step 6 FRICTION FEEDBACK NUDGE one-line cross-reference back to step 3 (CHANGE learned-append-gate / spec-learned-append-gate); the edit is inside TEST-010's live .aai/*.prompt.md glob, measured growth 755 B (348368 -> 349123), credited 1:1 to keep headroom unchanged at 636 within the 2048 cap; FRICTION_PROTOCOL.md's new 'Learned-append gate' pointer section carries no ledger cost (system/, not corpus)"
  "131 prompt-hash-runtime-wiring SKILL_LOOP.prompt.md step 4 one-line pointer (Dispatch printed \`Prompt hash: <hex>\`? Pass the full hex as \`--prompt-hash\` on this role's append-run) closing the producer/consumer gap left by PR #170 (prompt-hash-telemetry); the edit is inside TEST-010's live .aai/*.prompt.md glob, measured growth 131 B (349123 -> 349254), credited 1:1 to keep headroom unchanged at 636 within the 2048 cap"
  "286 state-bootstrap-template SKILL_CHECK_STATE.prompt.md AUTHORITATIVE SCHEMA paragraph reworded to name the new tracked .aai/templates/STATE_TEMPLATE.yaml (not the gitignored docs/ai/STATE.yaml) as the canonical schema source, with a pin requiring the live file's header to match it verbatim (CHANGE-0074/spec-state-bootstrap-template); the edit is inside TEST-010's live .aai/*.prompt.md glob, measured growth 286 B (349254 -> 349540), credited 1:1 to keep headroom unchanged at 636 within the 2048 cap"
  "-7475 doctor-determinize RECLAIMED credit (NEGATIVE entry, CHANGE-0079): .aai/SKILL_DOCTOR.prompt.md rewritten from a 10697 B prose file (11 of 13 categories were file-existence/line-count/git-status prose the LLM re-derived by hand every run) to a 3163 B thin wrapper that runs the new deterministic .aai/scripts/aai-doctor.mjs and relays its output (CAT-11/CAT-13 keep calling docs-audit.mjs/layer-drift.mjs exactly as before, now from inside the script) shrank the live .aai/*.prompt.md glob by the measured 7534 B (339967 -> 332433); the new engine itself lives outside the glob (.aai/scripts/, no ledger cost); without reconciliation headroom would jump 636 -> 8170, breaching HEADROOM_CAP=2048; this entry retires exactly 7534 B of credit so headroom lands back at 636 within the cap (per TEST-010's own remediation message: the corpus legitimately shrank below the credit, so LOWER JUSTIFIED_GROWTH_BYTES)"
  "210 session-loose-ends AGENTS.md degrade-with-NOTE convention (promptbook adoption 5 promoted to universal rule: any generator/gate that skips/excludes/degrades an input MUST name it in output — silent truncation is a defect); AGENTS.md sits outside TEST-010 live glob per the friction-shadow-capture-wiring precedent, credited manually at the exact +210 B AGENTS delta"
  "-2132 journal-report-contracts RECLAIMED credit (NEGATIVE entry, CHANGE-0080 + CHANGE-0082): SKILL_SESSION_JOURNAL.prompt.md relaxed from the once-used-and-same-day-deleted strict contract (SESSION-<slug> naming, 14-element template, 6-column INDEX) to the living convention (date-slug files, free form, 3-column INDEX, INDEX-completeness pin test_091), 4881 -> 2166 B (-2715); SKILL_VALIDATE_REPORT.prompt.md gained the opt-in SCOPE NOTE + unified VALIDATION-<ts>-<slug>.md naming, 2441 -> 3024 B (+583 incl. the STATE-sync line unified to the same naming); net glob shrink 2132 B; this entry retires exactly that credit so headroom stays at 605/2048 — the 605 (not 636) baseline reflects the +31 B PR #180 5d wording fix to SKILL_DOCS_HUB absorbed in slack (operator decisions 2026-07-28)"
  "-21517 dashboard-refit RECLAIMED credit (NEGATIVE entry, CHANGE-0076): .aai/SKILL_DASHBOARD.prompt.md rewritten from a 19173 B file (~330 of 652 lines were a stale duplicate implementation dump of .aai/scripts/generate-dashboard.mjs, which had diverged, plus a documented-but-unimplemented --publish flag and legacy-only METRICS schema docs) to a 4152 B script-first thin wrapper documenting both real input shapes (work-item ledger primary + legacy flat) and pointing publish at /aai-share; .aai/SKILL_TEST_SKILLS.prompt.md rewritten from a 9218 B file (stale hardcoded 11-skill Example Output block + a pytest/cargo CI snippet the project does not use) to a 2674 B wrapper around the real tests/skills/test-framework.sh, replacing the hardcoded count with a live 'ls tests/skills/test-aai-*.sh | wc -l' instruction; combined shrank the live .aai/*.prompt.md glob by a measured 21517 B net (332492 -> 310975: 21565 B initial rewrite minus 48 B review remediation replacing the no-op --fix repair claim with honest wording); without reconciliation headroom would jump 636 -> 22153, breaching HEADROOM_CAP=2048; this entry retires exactly 21517 B of credit so headroom lands back at 636 within the cap (per TEST-010's own remediation message: the corpus legitimately shrank below the credit, so LOWER JUSTIFIED_GROWTH_BYTES) — JUSTIFIED_GROWTH_BYTES going negative (14263 -> -7254) is expected and allowed (TEST-013's leading-field regex accepts a '-' sign); it reflects that the corpus has shrunk enough that no positive credit is owed at all"
  "-6099 docs-hub-generator RECLAIMED credit (NEGATIVE entry, CHANGE-0078): .aai/SKILL_DOCS_HUB.prompt.md rewritten from a 9513 B file (a ~70-file LLM fan-out prompt that hand-authored docs/SKILL_CATALOG.html per run, drifted to 27/35 skills stale by 2026-07-07) to a 3409 B script-first thin wrapper around the new deterministic .aai/scripts/generate-docs-hub.mjs (mechanical SKILL.md-frontmatter + prompt-Goal-section extraction, byte-idempotent, live .claude/skills count pin) shrank the live .aai/*.prompt.md glob by a measured 6099 B net (310975 -> 304876); the new engine itself lives outside the glob (.aai/scripts/, no ledger cost); without reconciliation headroom would jump 636 -> 6735, breaching HEADROOM_CAP=2048; this entry retires exactly 6099 B of credit so headroom lands back at 636 within the cap (per TEST-010's own remediation message: the corpus legitimately shrank below the credit, so LOWER JUSTIFIED_GROWTH_BYTES)"
  "3277 platform-portable-pr SKILL_PR.prompt.md step 5 PLATFORM GATE (runs the new .aai/scripts/pr-platform.mjs before branching gh/az/GENERIC MODE) + az repos pr create/reviewer add/thread list/thread create command set + step 5d REVIEWER-FALLBACK CONTRACT (no-external-reviewer-bots dispatch of SKILL_CODE_REVIEW.prompt.md is REQUIRED, findings published as PR threads with a closing reply citing the fixing commit) + GENERIC MODE loud line for unknown/no-remote hosts (CHANGE-0085-platform-portable-pr / SPEC-0103-spec-platform-portable-pr, operator direction 2026-07-28); the edit is inside TEST-010's live .aai/*.prompt.md glob, measured growth 3277 B (13767 -> 17044 B), credited 1:1 to keep headroom unchanged at 605 within the 2048 cap"
  "3810 issues-skill new .aai/SKILL_ISSUES.prompt.md thin wrapper (CHANGE-0087-issues-skill / SPEC-0104-spec-issues-skill.md) documenting the on-demand /aai-issues fetch+triage skill (runs .aai/scripts/aai-issues.mjs, reuses pr-platform.mjs classification, closed bug/feature/question/duplicate triage taxonomy, ONE operator approval checkpoint, write-back-only-after-merge contract, UNTRUSTED-DATA and never-in-loop rules pinned verbatim); the whole new file is inside TEST-010's live .aai/*.prompt.md glob (3810 B, measured via `wc -c .aai/SKILL_ISSUES.prompt.md`), measured deficit 2734 B after consuming the prior 815 B headroom, credited at the true +3810 B growth (== the file's exact size, since this scope adds no other prompt-corpus bytes), headroom back to 815 within the 2048 cap"
  "1147 github-no-bots-hardening SKILL_PR.prompt.md step 5 PLATFORM GATE reviewer_bots note (probe now prints reviewer_bots=<expected|none|unknown> from docs/ai/pr-config.yaml; absent == none, assume-none) + step 5d BOUNDED-WAIT rule (even with reviewer_bots == expected, after CI green wait a bounded window, default 10 min, then fall through; the sweep never waits forever for Copilot/Codex comments that never arrive on a GitHub repo with no bots) + REVIEWER-FALLBACK CONTRACT detection widened from platform != github to zero bot-authored threads AND reviewer_bots != expected, so a GitHub repo whose knob is none/unknown/absent takes the internal-review fallback exactly like Azure (CHANGE-DRAFT-github-no-bots-hardening, follow-up to CHANGE-0085/SPEC-0103); the edit is inside TEST-010's live .aai/*.prompt.md glob, measured growth 1147 B (16740 -> 17887 B), credited 1:1 to keep headroom unchanged at 106 within the 2048 cap"
  "-3247 core-prompt-diet RECLAIMED credit (NEGATIVE entry, CHANGE-DRAFT-core-prompt-diet): folded 4 cross-prompt duplications into .aai/ROLE_COMMON.md as canonical blocks (mirroring the existing METRICS block) — FRICTION HOOK (IMPLEMENTATION + VALIDATION x2 + REMEDIATION), PYTHON MONTY SCRATCHPAD (IMPLEMENTATION + SKILL_TDD), PRE-HANDOFF AC-TABLE RECONCILIATION (IMPLEMENTATION + SKILL_TDD), WORKTREE GATE (ORCHESTRATION_PARALLEL + IMPLEMENTATION + SKILL_TDD) — each former site reduced to a pointer + its role-specific verb, though the 4 FRICTION HOOK sites also keep their own literal .aai/system/FRICTION_PROTOCOL.md + best-effort wording (test-aai-friction-wiring.sh TEST-009/TEST-011 hostile-mutation pins require each owning prompt, not just ROLE_COMMON.md, to carry a live, greppable pointer); deleted SKILL_TDD.prompt.md's 3 dead prose-only sections (Token Optimization, Example Complete Cycle, Troubleshooting -> 1-line pointer to SKILL_DEBUG.prompt.md); trimmed SKILL_LOOP's VALIDATOR INDEPENDENCE rationale tail to a pointer at SUBAGENT_PROTOCOL.md's \"Spawning a validator in a separate agent\" (the dispatch-payload sentence naming .aai/SUBAGENT_CONTRACT.md is kept verbatim — hygiene-pack TEST-082/spec-subagent-protocol-slim TEST-003 pins it as CONTRACT-only, not a PROTOCOL duplicate), trimmed its LOOP PARAMETERS run-budget bullet to a back-pointer at step 2f, and trimmed POST-TICK REAP's rationale to a pointer at aai-reap-tests.sh's header (env-var/when-to-run instructions kept verbatim); pointed SKILL_CHECK_STATE's INV-14 DETECT/REPAIR prose at check-state.mjs's header (WRITER RULE line kept verbatim); pointed SKILL_PR's RECONCILE WORKTREE TELEMETRY rationale at reconcile-telemetry.mjs's header PURPOSE (exit-code branching kept verbatim); pointed VALIDATION's LEAK-SAFE EXECUTION rationale at the aai-run-tests.sh/aai-reap-tests.sh headers (the AAI_REAP_STEP_START_EPOCH capture + wrapper invocation recipe kept verbatim); trimmed ORCHESTRATION_PARALLEL's SCOPE LOCKING TTL/exit-code prose to a pointer at docs-lock.mjs's header (the acquire/release call pattern + exit-code branches kept verbatim); shrank the live .aai/*.prompt.md glob by a measured 6442 B (310175 -> 303733) while growing .aai/ROLE_COMMON.md (already inside TEST-010's extra accounting) by 3195 B (1666 -> 4861); without reconciliation headroom would jump 502 -> 3749, breaching HEADROOM_CAP=2048; this entry retires exactly 3247 B (6442 minus 3195) of credit so headroom lands back at 502 within the cap (per TEST-010's own remediation message: the corpus legitimately shrank below the credit, so LOWER JUSTIFIED_GROWTH_BYTES)"
  "282 CHANGE-0096-botfix SKILL_PR 5d bot-review hardening reword (P1: the empty-sweep stop now requires a bot-authored review to EXIST — zero bot activity is never a stop while the bounded window is open; poll-once wording replaced by re-poll-within-window) added 282 B of load-bearing gating prose beyond the prior +1147 credit; credited at the true +282 B growth, measured against TEST-010 floor deficit 282 B"
  "4774 implementation-mode-choice user-facing implementation-mode choice surfaced at end of intake + honored downstream (SPEC spec-implementation-mode-choice, ceremony_level 3): .aai/INTAKE_COMMON.md IMPLEMENTATION MODE CHOICE block (3-way choice full-TDD/direct+tests/direct-without-tests + signal-derived recommendation + set-strategy --source intake recording + back-compat no-choice path) + SKILL_INTAKE STEP 3.5 and five-blocks reference + PLANNING step 7 RESPECT-A-PRE-RECORDED-INTAKE-CHOICE clause and set-strategy enum extension + IMPLEMENTATION step 4 direct/untested lanes + SKILL_TDD Phase-0 step 5 non-TDD-lane hand-off + VALIDATION STRATEGY-CONDITIONAL EVIDENCE block and 5g pointer; the state.mjs/orchestration-dispatch.mjs enum + untested-rationale guard live in .aai/scripts/ (no ledger cost); the prose edits are inside TEST-010's live .aai/*.prompt.md glob + INTAKE_COMMON extra accounting, measured deficit 4774 B, credited 1:1 so headroom stays 0 within the 2048 cap"
  "854 implementation-mode-choice-botfix P1/P2 bot-review + owner-UX fixes on the implementation-mode ride: INTAKE_COMMON fresh-checkout fallback (record the choice in the intake artifact Notes when docs/ai/STATE.yaml does not exist yet — set-strategy would fail), PLANNING respect-clause extension covering that doc-note, SKILL_INTAKE choice step moved BEFORE the INTAKE COMPLETE output (post-completion ask gets skipped) with its ordering rationale, SKILL_CHECK_STATE INV-11 enum += direct/untested (a recorded lane must not FAIL state health); plus the explicit option 4 (Let Planning decide — never rely on detecting silence; owner UX feedback); measured deficit 853 B after the prior entry consumed headroom to 0, credited at the true +854 B growth (Planning-default listed first per owner)"
)
JUSTIFIED_GROWTH_BYTES=0
for _entry in "${JUSTIFIED_ADDITIONS[@]}"; do
  JUSTIFIED_GROWTH_BYTES=$(( JUSTIFIED_GROWTH_BYTES + ${_entry%% *} ))
done
unset _entry   # do not leak the loop scratch var into the sourcing shell
# Anti-bloat guard (TEST-002/Spec-AC-02): headroom must stay in
# [0, HEADROOM_CAP] so the credit cannot be padded arbitrarily and future
# UNJUSTIFIED prompt growth beyond the cap still fails this test (forcing a
# new itemized ledger line, or a shrink, instead of a silent absorption).
HEADROOM_CAP=2048

# Pure helpers factored out of TEST-010 (Spec-AC-02/SPEC-0059) so synthetic
# fixtures can drive them with SYNTHETIC inputs, proving the breach-deficit
# template and the cap-bite guard WITHOUT mutating the real
# JUSTIFIED_ADDITIONS ledger or reading the live corpus.

# compute_reduction_headroom <baseline> <after> <extra> <credit> <required>
# Mirrors TEST-010's exact formula; echoes "<reduction> <headroom>".
compute_reduction_headroom() {
  local baseline=$1 after=$2 extra=$3 credit=$4 required=$5
  local reduction=$(( baseline - after - extra + credit ))
  local headroom=$(( reduction - required ))
  echo "$reduction $headroom"
}

# justified_growth_breach_suggestion <reduction> <required>
# Computes the exact deficit and echoes a ready-to-paste ledger-entry line.
justified_growth_breach_suggestion() {
  local reduction=$1 required=$2
  local deficit=$(( required - reduction ))
  echo "JUSTIFIED_ADDITIONS+=( \"$deficit <REF-ID> <rationale>\" )"
}
