# Shared prompt-diet byte-floor ledger (prompt-diet-floor-credit-drift /
# SPEC-DRAFT-spec-prompt-diet-floor-credit-drift.md).
#
# Single sourceable definition of the diet-floor constants, the
# JUSTIFIED_ADDITIONS ledger, and the two pure helpers, so
# tests/skills/test-aai-prompt-diet.sh and tests/skills/test-aai-verify-gate.sh
# can never drift from each other again (DEBT-0002 "two copies of one gate"
# pattern; docs/knowledge/LEARNED.md 2026-07-17).
#
# This file is a PURE library: no `set -u`, no `cd`, no test execution. It is
# only ever sourced, never run directly. bash-3.2 / Windows-Git-Bash safe: no
# `bc`, no `mapfile`, no `declare -A`.

# Byte baseline measured before any CHANGE-0011 edit (evidence:
# docs/ai/tdd/prompt-diet-kb-before.txt). AC floor: >= 28KB net reduction.
# BASELINE_PROMPT_BYTES and REQUIRED_REDUCTION_BYTES are the historical
# SPEC-0017 diet contract and stay UNCHANGED (DEBT-0002/SPEC-0048): rewriting
# them to match live measurements would erase history and IS the
# blank-raise anti-pattern the floor exists to prevent.
BASELINE_PROMPT_BYTES=357457
REQUIRED_REDUCTION_BYTES=28672   # 28 KB

# --- Justified-growth ledger (DEBT-0002/SPEC-0048 -> CHANGE-0040/SPEC-0059) -
# Canon-mandated prompt additions AFTER the SPEC-0017 diet legitimately grew
# the corpus. JUSTIFIED_GROWTH_BYTES is no longer a manually-bumped magic
# number: it is the portable bash-3.2 sum of the leading `<bytes>` field of
# each JUSTIFIED_ADDITIONS entry below (no bc, no mapfile, no declare -A --
# just `${_entry%% *}` + `$(( ))`, so it also runs under the Windows/Git-Bash
# matrix). Each entry is self-documenting: "<bytes> <ref> <rationale>".
# Adding a new legitimate prompt addition is a one-line array append with its
# own audit trail, not a recomputed constant (source: DEBT-0002 root cause,
# docs/knowledge/LEARNED.md 2026-07-17; true-up history: ISSUE-0016).
# DIET 2026-08-02 (CHANGE-DRAFT-prompt-diet-2026-08): trimmed 1530 B of dead
# weight out of the three largest corpus prompts — SKILL_LOOP -1297 (six
# U+2500 box rules -> `---`; the LOOP PARAMETERS stop_conditions copy -> a
# pointer at its single definition in step 2), VALIDATION -209 (AC STATUS GATE
# paragraph + `Detection:` list said the opt-in rule twice, merged), SKILL_PR
# -24 (duplicate pr-platform.mjs re-invocation in step 5). NO ledger entry and
# NO credit change: per TEST-010's remediation rule the credit is lowered only
# when a shrink would push headroom ABOVE HEADROOM_CAP. 1530 < 2048, so the
# trim is absorbed as headroom (0 -> 1530) and JUSTIFIED_GROWTH_BYTES stays
# 1116 (TEST-012 pin unchanged). This slack exists to be spent by the next
# justified additions — not to be re-padded.
JUSTIFIED_ADDITIONS=(
  "6144 DEBT-0002 dual-verdict code-review taxonomy + VALIDATION 8a exception + CEREMONY LANE block (SPEC-0041) + RED_CLASS discipline (SPEC-0044) + SECRETS PREFLIGHT (SPEC-0045) + doc-number origin reservation (SPEC-0047) + ceremony-lane declaration surfaces (SPEC_TEMPLATE/PLANNING/WORKFLOW); measured deficit 5122 B, credit chosen 6144 B for 1022 B headroom"
  "1309 CHANGE-0037 deterministic close-ceremony wiring prose: SKILL_PR.prompt.md step 5c close-work-item.mjs invocation (+1144 B) + VALIDATION 8b hand-flip/hand-emit removal replaced by close-ceremony pointer (+165 B)"
  "1786 CHANGE-0038+0039 workflow-hardening wiring prose: METRICS_FLUSH.prompt.md rewrite (flush no longer emits close events, SPEC-0054) + SKILL_PR step 2b RECONCILE WORKTREE TELEMETRY invocation prose (SPEC-0055)"
  "3100 aai-release-skill new .aai/SKILL_RELEASE.prompt.md thin-wrapper prompt (SPEC-DRAFT-spec-aai-release-skill D9) documenting the /aai-release deterministic release-cut engine (--dry-run/--version/--confirm/--no-remote), mirroring SKILL_UPDATE.prompt.md's shape; measured deficit 3027 B, credit chosen 3100 B for 73 B headroom"
  "825 reaper-deterministic-age-guard SKILL_LOOP.prompt.md POST-TICK REAP + VALIDATION.prompt.md step-boundary reap prose documenting the step owner's AAI_REAP_STEP_START_EPOCH=\$(date +%s) capture/handoff to the reaper's deterministic epoch guard; measured deficit 825 B, credit chosen 825 B for 0 B headroom"
  "5396 hitl-decision-propagation SKILL_HITL.prompt.md STEP 4c trigger->target mapping table + normalization table + fail-closed rule + write-ordering rule (replacing the old absolute STATE-field prohibition) + ORCHESTRATION_HITL.prompt.md [HITL-<n>] blocking_reason stamping prose (SPEC-DRAFT-spec-hitl-decision-propagation); measured deficit 4848 B + 548 B code-review remediation (scope FAIL-CLOSED to enum targets so HITL-1..6/8 cannot deadlock; sanction set-human-input for the STEP 5 clear so the narrowed guardrail cannot forbid the resolver's own job); credit chosen 5396 B for 0 B headroom"
  "738 metrics-flush-strands-completed-refs METRICS_FLUSH.prompt.md RUN step 1 one-line --sweep mention (opt-in durable-provenance multi-ref flush of stranded work items, SPEC-DRAFT-spec-metrics-flush-sweep) + --events NO-OP caveat update; measured deficit 418 B initial + 320 B code-review reword, credit chosen 738 B for 0 B headroom"
  "494 branch-per-work-item-hygiene SKILL_PR.prompt.md '0. BRANCH HYGIENE' precondition (runs branch-guard.mjs, fail-closed, STOPS before push on a mis-branched scope) + AGENTS.md one-branch-per-work-item rule naming the guard (ISSUE-0024/SPEC-0070); measured deficit 494 B, credit chosen 494 B for 0 B headroom"
  "566 planning-companion-obligations PLANNING.prompt.md step 3a COMPANION OBLIGATIONS CHECK (closed two-entry planner checklist: prompt-corpus byte growth -> prompt-diet ledger true-up; new .aai/** file -> PROFILES.yaml classification), self-dogfooding the rule it introduces (SPEC-DRAFT-spec-planning-companion-obligations); measured deficit 566 B, credit chosen 566 B for 0 B headroom"
  "488 friction-shadow-capture-wiring AGENTS.md '### Friction capture (shadow)' thin inheriting pointer to the FRICTION_PROTOCOL.md 'Skill wiring (shadow capture)' seam (RFC-0012 Phase 1, SPEC-DRAFT-spec-friction-shadow-capture-wiring); AGENTS.md is prompt corpus per PLANNING step 3a but sits outside TEST-010's live .aai/*.prompt.md glob, so its 488 B growth carries no MEASURED deficit — credited manually at exactly the +488 B AGENTS.md delta (18425 -> 18913) to keep the corpus-as-defined reduction honest, headroom 0 -> 488 within the 2048 cap. The seam BODY lives in .aai/system/FRICTION_PROTOCOL.md (system/, not corpus, no ledger cost)"
  "1486 feedback-triage-offline new .aai/SKILL_FEEDBACK_TRIAGE.prompt.md thin wrapper (RFC-0012 Phase 2 / RFC-0013 Slice B, SPEC-DRAFT-spec-feedback-triage-offline) documenting the offline /aai-feedback-triage engine (spool -> gates -> v2-signal scoring -> fingerprint clustering -> local report, no network), mirroring SKILL_UPDATE's thin-wrapper shape; the 1486 B prompt is inside TEST-010's live .aai/*.prompt.md glob (measured deficit 998 B after consuming the prior 488 B headroom), credited at the true +1486 B growth so JUSTIFIED_GROWTH tracks the actual corpus addition, headroom back to 488 within the 2048 cap"
  "608 friction-feedback-discovery SKILL_WRAP_UP.prompt.md step 6 FRICTION FEEDBACK NUDGE (runs aai-feedback-status.mjs at session end to surface captured observations / pending --confirm drafts / gh auth state, silent when nothing captured; RFC-0012 discovery, SPEC-DRAFT-spec-friction-feedback-discovery); 608 B inside TEST-010's live .aai/*.prompt.md glob (measured deficit 120 B after the prior 488 B headroom), credited at the true +608 B growth, headroom back to 488 within the 2048 cap"
  "1931 feedback-upsert-review new .aai/SKILL_FEEDBACK_UPSERT.prompt.md thin wrapper (RFC-0012 Phase 2c / Slice C, SPEC-DRAFT-spec-feedback-upsert-review) documenting the review-mode /aai-feedback-upsert engine (prepare-only default; --publish <fp> --confirm the ONLY GitHub write; transmit-pass redaction reuse; v1:<fp> dedup marker; budget ledger; destination pin); the 1931 B prompt is inside TEST-010's live .aai/*.prompt.md glob (measured deficit 1443 B after consuming the prior 488 B headroom), credited at the true +1931 B growth, headroom back to 488 within the 2048 cap"
  "535 prune-stale-briefs SKILL_WRAP_UP.prompt.md step 6b STALE-BRIEF SWEEP (runs prune-stale-briefs.mjs at session end to prune terminal/orphan work-item briefs while KEEPING live handoffs, no-op when clean; AAI docs-lifecycle hygiene, CHANGE-DRAFT-prune-stale-briefs); the 535 B step is inside TEST-010's live .aai/*.prompt.md glob (measured deficit 47 B after consuming the prior 488 B headroom), credited at the true +535 B growth, headroom back to 488 within the 2048 cap"
  "3336 auditor-autonomy-pack new .aai/SKILL_SHIP.prompt.md end-to-end autopilot composition prompt (3201 B: need -> intake -> loop -> product docs -> ONE ship checkpoint -> PR, autopilot defaults recorded, never merges) + ORCHESTRATION.prompt.md / ORCHESTRATION_PARALLEL.prompt.md MODEL SELECTION suggested_model pointers to the .aai/system/MODEL_ROUTING.yaml deterministic tier->id binding (+15 B / +120 B; ORCHESTRATION held at 40 lines per the spec D5 cap); measured deficit 2848 B after consuming the prior 488 B headroom, credited at the true +3336 B growth, headroom back to 488 within the 2048 cap"
  "148 auditor-autonomy-pack AGENTS.md SKILL_SHIP listing line in the Universal Skills block — AGENTS.md sits outside TEST-010's live .aai/*.prompt.md glob, so the growth carries no MEASURED deficit; credited manually at the exact +148 B AGENTS.md delta (18913 -> 19061) to keep the corpus-as-defined reduction honest, headroom 488 -> 636 within the 2048 cap"
  "912 token-capture-canary SKILL_LOOP.prompt.md step 4 mandatory-usage-note reinforcement (usage_total_tokens=<N> non-optional at merge time) + step 6 MANDATORY --started/--harness wiring prose so log-tick's new duration/harness WARNINGs never fire on a correctly-wired tick (SPEC-DRAFT-spec-token-capture-canary Spec-AC-03); the edit is inside TEST-010's live .aai/*.prompt.md glob, measured growth 912 B (25941 -> 26853), credited 1:1 to keep headroom unchanged at 636 within the 2048 cap"
  "-3021 prompt-dedup-canonical-includes RECLAIMED credit (NEGATIVE entry, DEBT-0002/SPEC-0059 reconciliation): trimming PLANNING step 10's ceremony-level paraphrase to a WORKFLOW.md pointer + reducing VALIDATION's AC STATUS GATE Rules 1/2/4-format to a docs-audit.mjs --gate <ref> invocation (Rules 3/4-anti-cheat retained as prose, script does not compute them) + collapsing the D5 subagent-mode metrics/append-run boilerplate in PLANNING/IMPLEMENTATION/VALIDATION/REMEDIATION/SKILL_TDD to a pointer at the new .aai/ROLE_COMMON.md shrank the live .aai/*.prompt.md glob by a measured 4687 B (349697 -> 345010); .aai/ROLE_COMMON.md (1666 B) is added to TEST-010's extra accounting to neutralize the relocation, leaving a genuine 3021 B reduction (4687 minus 1666) that would otherwise push headroom from 636 to 3657, breaching HEADROOM_CAP=2048; this entry retires exactly that 3021 B of credit so headroom lands back at 636 within the cap (per TEST-010's own remediation message: the corpus legitimately shrank below the credit, so LOWER JUSTIFIED_GROWTH_BYTES)"
  "-9573 decapod-prune RECLAIMED credit (NEGATIVE entry, CHANGE-0077): deleting the dead .aai/SKILL_DECAPOD.prompt.md (9571 B file; retired 9573 B = 9571 B file + 2 B residual slack from the SPEC-0099 SKILL_CHECK_STATE reword credited at 286 but measuring 284; external decapod CLI never shipped, zero consumers since 2026-03 — skill-sweep group C evidence) shrank the live .aai/*.prompt.md glob accordingly; without reconciliation headroom jumps 636 -> 10209, breaching HEADROOM_CAP=2048; this entry retires exactly 9573 B of credit so headroom lands back at 636 within the cap (per TEST-010 remediation guidance: the corpus legitimately shrank below the credit, so LOWER JUSTIFIED_GROWTH_BYTES)"
  "992 pr-post-open-review-sweep SKILL_PR.prompt.md new step 5d POST-OPEN REVIEW SWEEP (operator-directed 2026-07-26): after gh pr create, poll bot inline comments post-CI (gh api pulls/<n>/comments + reviews); any findings route through the canonical EXTERNAL-REVIEW RESPONSE flow in SKILL_CODE_REVIEW.prompt.md (triage real/stale/duplicate/disputed, RED-proofed regression per real code finding, inline reply per thread — Codex P2 review on PR #160 replaced the original lighter duplicated triage path with this delegation, +97 B over the initial 895 B); wait for the CI re-run + one repeat sweep before any merge-readiness claim; merge boundary unchanged — promotes the PR #158/#159 review-response discipline (7+3 real bot findings fixed) from session memory to canon; measured deficit 356 B after consuming the prior 636 B headroom, credited at the true +992 B growth, headroom back to 636 within the 2048 cap"
  "32 subagent-protocol-slim SKILL_LOOP.prompt.md line-18 clause fix (code-review non-blocking finding disposition, review-20260726T184739Z): the AUTHORITATIVE SOURCES bullet no longer credits SUBAGENT_PROTOCOL.md with the result-block format (relocated to .aai/SUBAGENT_CONTRACT.md by CHANGE-0061) — reworded to name both files honestly; measured +32 B in the TEST-010 glob, credited at the true +32 B growth, headroom 636 -> 636 net across the CHANGE-0061 scope (all other edits byte-neutral renames)"
  "1881 friction-capture-default-on thin FRICTION HOOK pointers naming .aai/system/FRICTION_PROTOCOL.md's new 'Deterministic hook points' subsection (default-on best-effort capture at the moments AAI-owned friction is most salient, RFC-0012 root-cause finding): VALIDATION.prompt.md step 5h canon-file gate/lint/CI failure + step 8 validation-FAIL-recorded (+629 B), REMEDIATION.prompt.md step 1/2 remediation-dispatched (+288 B), SKILL_PR.prompt.md step 5d CI-check-failure-handled (+307 B), SKILL_WRAP_UP.prompt.md step 6 non-empty-spool triage + proposed-intake surfacing (+657 B) — the seam body itself lives in FRICTION_PROTOCOL.md (system/, not corpus, no ledger cost); measured deficit 1245 B after consuming the prior 636 B headroom, credited at the true +1881 B growth, headroom back to 636 within the 2048 cap"
  "453 friction-capture-default-on-r2 IMPLEMENTATION.prompt.md FRICTION HOOK (canon-surface check failure during implementation, default-on) — validation residual-risk R2 remediation: the ride's own motivating case (prompt-diet headroom-cap trap) fired during IMPLEMENTATION where no hook existed, so the class stayed uncaptured; thin pointer mirrors the VALIDATION 5h wording, swallow-and-never-mask contract unchanged; measured +453 B, credited at the true +453 B growth, headroom unchanged within the 2048 cap"
  "755 learned-append-gate SKILL_WRAP_UP.prompt.md step 3 PROPOSE NEW LEARNED RULES rewrite (confirmed rule now routes through a compact critic pass THEN the structural gate node .aai/scripts/learned-append.mjs --source/--text — never a direct edit) + step 6 FRICTION FEEDBACK NUDGE one-line cross-reference back to step 3 (CHANGE learned-append-gate / spec-learned-append-gate); the edit is inside TEST-010's live .aai/*.prompt.md glob, measured growth 755 B (348368 -> 349123), credited 1:1 to keep headroom unchanged at 636 within the 2048 cap; FRICTION_PROTOCOL.md's new 'Learned-append gate' pointer section carries no ledger cost (system/, not corpus)"
  "131 prompt-hash-runtime-wiring SKILL_LOOP.prompt.md step 4 one-line pointer (Dispatch printed \`Prompt hash: <hex>\`? Pass the full hex as \`--prompt-hash\` on this role's append-run) closing the producer/consumer gap left by PR #170 (prompt-hash-telemetry); the edit is inside TEST-010's live .aai/*.prompt.md glob, measured growth 131 B (349123 -> 349254), credited 1:1 to keep headroom unchanged at 636 within the 2048 cap"
  "286 state-bootstrap-template SKILL_CHECK_STATE.prompt.md AUTHORITATIVE SCHEMA paragraph reworded to name the new tracked .aai/templates/STATE_TEMPLATE.yaml (not the gitignored docs/ai/STATE.yaml) as the canonical schema source, with a pin requiring the live file's header to match it verbatim (CHANGE-0074/spec-state-bootstrap-template); the edit is inside TEST-010's live .aai/*.prompt.md glob, measured growth 286 B (349254 -> 349540), credited 1:1 to keep headroom unchanged at 636 within the 2048 cap"
  "-7475 doctor-determinize RECLAIMED credit (NEGATIVE entry, CHANGE-0079): .aai/SKILL_DOCTOR.prompt.md rewritten from a 10697 B prose file (11 of 13 categories were file-existence/line-count/git-status prose the LLM re-derived by hand every run) to a 3163 B thin wrapper that runs the new deterministic .aai/scripts/aai-doctor.mjs and relays its output (CAT-11/CAT-13 keep calling docs-audit.mjs/layer-drift.mjs exactly as before, now from inside the script) shrank the live .aai/*.prompt.md glob by the measured 7534 B (339967 -> 332433); the new engine itself lives outside the glob (.aai/scripts/, no ledger cost); without reconciliation headroom would jump 636 -> 8170, breaching HEADROOM_CAP=2048; this entry retires exactly 7534 B of credit so headroom lands back at 636 within the cap (per TEST-010's own remediation message: the corpus legitimately shrank below the credit, so LOWER JUSTIFIED_GROWTH_BYTES)"
  "210 session-loose-ends AGENTS.md degrade-with-NOTE convention (promptbook adoption 5 promoted to universal rule: any generator/gate that skips/excludes/degrades an input MUST name it in output — silent truncation is a defect); AGENTS.md sits outside TEST-010 live glob per the friction-shadow-capture-wiring precedent, credited manually at the exact +210 B AGENTS delta"
  "-2132 journal-report-contracts RECLAIMED credit (NEGATIVE entry, CHANGE-0080 + CHANGE-0082): SKILL_SESSION_JOURNAL.prompt.md relaxed from the once-used-and-same-day-deleted strict contract (SESSION-<slug> naming, 14-element template, 6-column INDEX) to the living convention (date-slug files, free form, 3-column INDEX, INDEX-completeness pin test_091), 4881 -> 2166 B (-2715); SKILL_VALIDATE_REPORT.prompt.md gained the opt-in SCOPE NOTE + unified VALIDATION-<ts>-<slug>.md naming, 2441 -> 3024 B (+583 incl. the STATE-sync line unified to the same naming); net glob shrink 2132 B; this entry retires exactly that credit so headroom stays at 605/2048 — the 605 (not 636) baseline reflects the +31 B PR #180 5d wording fix to SKILL_DOCS_HUB absorbed in slack (operator decisions 2026-07-28)"
  "-21517 dashboard-refit RECLAIMED credit (NEGATIVE entry, CHANGE-0076): .aai/SKILL_DASHBOARD.prompt.md rewritten from a 19173 B file (~330 of 652 lines were a stale duplicate implementation dump of .aai/scripts/generate-dashboard.mjs, which had diverged, plus a documented-but-unimplemented --publish flag and legacy-only METRICS schema docs) to a 4152 B script-first thin wrapper documenting both real input shapes (work-item ledger primary + legacy flat) and pointing publish at /aai-share; .aai/SKILL_TEST_SKILLS.prompt.md rewritten from a 9218 B file (stale hardcoded 11-skill Example Output block + a pytest/cargo CI snippet the project does not use) to a 2674 B wrapper around the real tests/skills/test-framework.sh, replacing the hardcoded count with a live 'ls tests/skills/test-aai-*.sh | wc -l' instruction; combined shrank the live .aai/*.prompt.md glob by a measured 21517 B net (332492 -> 310975: 21565 B initial rewrite minus 48 B review remediation replacing the no-op --fix repair claim with honest wording); without reconciliation headroom would jump 636 -> 22153, breaching HEADROOM_CAP=2048; this entry retires exactly 21517 B of credit so headroom lands back at 636 within the cap (per TEST-010's own remediation message: the corpus legitimately shrank below the credit, so LOWER JUSTIFIED_GROWTH_BYTES) — JUSTIFIED_GROWTH_BYTES going negative (14263 -> -7254) is expected and allowed (TEST-013's leading-field regex accepts a '-' sign); it reflects that the corpus has shrunk enough that no positive credit is owed at all"
  "-6099 docs-hub-generator RECLAIMED credit (NEGATIVE entry, CHANGE-0078): .aai/SKILL_DOCS_HUB.prompt.md rewritten from a 9513 B file (a ~70-file LLM fan-out prompt that hand-authored docs/SKILL_CATALOG.html per run, drifted to 27/35 skills stale by 2026-07-07) to a 3409 B script-first thin wrapper around the new deterministic .aai/scripts/generate-docs-hub.mjs (mechanical SKILL.md-frontmatter + prompt-Goal-section extraction, byte-idempotent, live .claude/skills count pin) shrank the live .aai/*.prompt.md glob by a measured 6099 B net (310975 -> 304876); the new engine itself lives outside the glob (.aai/scripts/, no ledger cost); without reconciliation headroom would jump 636 -> 6735, breaching HEADROOM_CAP=2048; this entry retires exactly 6099 B of credit so headroom lands back at 636 within the cap (per TEST-010's own remediation message: the corpus legitimately shrank below the credit, so LOWER JUSTIFIED_GROWTH_BYTES)"
  "3277 platform-portable-pr SKILL_PR.prompt.md step 5 PLATFORM GATE (runs the new .aai/scripts/pr-platform.mjs before branching gh/az/GENERIC MODE) + az repos pr create/reviewer add/thread list/thread create command set + step 5d REVIEWER-FALLBACK CONTRACT (no-external-reviewer-bots dispatch of SKILL_CODE_REVIEW.prompt.md is REQUIRED, findings published as PR threads with a closing reply citing the fixing commit) + GENERIC MODE loud line for unknown/no-remote hosts (CHANGE-0085-platform-portable-pr / SPEC-0103-spec-platform-portable-pr, operator direction 2026-07-28); the edit is inside TEST-010's live .aai/*.prompt.md glob, measured growth 3277 B (13767 -> 17044 B), credited 1:1 to keep headroom unchanged at 605 within the 2048 cap"
  "3810 issues-skill new .aai/SKILL_ISSUES.prompt.md thin wrapper (CHANGE-0087-issues-skill / SPEC-0104-spec-issues-skill.md) documenting the on-demand /aai-issues fetch+triage skill (runs .aai/scripts/aai-issues.mjs, reuses pr-platform.mjs classification, closed bug/feature/question/duplicate triage taxonomy, ONE operator approval checkpoint, write-back-only-after-merge contract, UNTRUSTED-DATA and never-in-loop rules pinned verbatim); the whole new file is inside TEST-010's live .aai/*.prompt.md glob (3810 B, measured via `wc -c .aai/SKILL_ISSUES.prompt.md`), measured deficit 2734 B after consuming the prior 815 B headroom, credited at the true +3810 B growth (== the file's exact size, since this scope adds no other prompt-corpus bytes), headroom back to 815 within the 2048 cap"
  "1147 github-no-bots-hardening SKILL_PR.prompt.md step 5 PLATFORM GATE reviewer_bots note (probe now prints reviewer_bots=<expected|none|unknown> from docs/ai/pr-config.yaml; absent == none, assume-none) + step 5d BOUNDED-WAIT rule (even with reviewer_bots == expected, after CI green wait a bounded window, default 10 min, then fall through; the sweep never waits forever for Copilot/Codex comments that never arrive on a GitHub repo with no bots) + REVIEWER-FALLBACK CONTRACT detection widened from platform != github to zero bot-authored threads AND reviewer_bots != expected, so a GitHub repo whose knob is none/unknown/absent takes the internal-review fallback exactly like Azure (CHANGE-DRAFT-github-no-bots-hardening, follow-up to CHANGE-0085/SPEC-0103); the edit is inside TEST-010's live .aai/*.prompt.md glob, measured growth 1147 B (16740 -> 17887 B), credited 1:1 to keep headroom unchanged at 106 within the 2048 cap"
  "-3247 core-prompt-diet RECLAIMED credit (NEGATIVE entry, CHANGE-DRAFT-core-prompt-diet): folded 4 cross-prompt duplications into .aai/ROLE_COMMON.md as canonical blocks (mirroring the existing METRICS block) — FRICTION HOOK (IMPLEMENTATION + VALIDATION x2 + REMEDIATION), PYTHON MONTY SCRATCHPAD (IMPLEMENTATION + SKILL_TDD), PRE-HANDOFF AC-TABLE RECONCILIATION (IMPLEMENTATION + SKILL_TDD), WORKTREE GATE (ORCHESTRATION_PARALLEL + IMPLEMENTATION + SKILL_TDD) — each former site reduced to a pointer + its role-specific verb, though the 4 FRICTION HOOK sites also keep their own literal .aai/system/FRICTION_PROTOCOL.md + best-effort wording (test-aai-friction-wiring.sh TEST-009/TEST-011 hostile-mutation pins require each owning prompt, not just ROLE_COMMON.md, to carry a live, greppable pointer); deleted SKILL_TDD.prompt.md's 3 dead prose-only sections (Token Optimization, Example Complete Cycle, Troubleshooting -> 1-line pointer to SKILL_DEBUG.prompt.md); trimmed SKILL_LOOP's VALIDATOR INDEPENDENCE rationale tail to a pointer at SUBAGENT_PROTOCOL.md's \"Spawning a validator in a separate agent\" (the dispatch-payload sentence naming .aai/SUBAGENT_CONTRACT.md is kept verbatim — hygiene-pack TEST-082/spec-subagent-protocol-slim TEST-003 pins it as CONTRACT-only, not a PROTOCOL duplicate), trimmed its LOOP PARAMETERS run-budget bullet to a back-pointer at step 2f, and trimmed POST-TICK REAP's rationale to a pointer at aai-reap-tests.sh's header (env-var/when-to-run instructions kept verbatim); pointed SKILL_CHECK_STATE's INV-14 DETECT/REPAIR prose at check-state.mjs's header (WRITER RULE line kept verbatim); pointed SKILL_PR's RECONCILE WORKTREE TELEMETRY rationale at reconcile-telemetry.mjs's header PURPOSE (exit-code branching kept verbatim); pointed VALIDATION's LEAK-SAFE EXECUTION rationale at the aai-run-tests.sh/aai-reap-tests.sh headers (the AAI_REAP_STEP_START_EPOCH capture + wrapper invocation recipe kept verbatim); trimmed ORCHESTRATION_PARALLEL's SCOPE LOCKING TTL/exit-code prose to a pointer at docs-lock.mjs's header (the acquire/release call pattern + exit-code branches kept verbatim); shrank the live .aai/*.prompt.md glob by a measured 6442 B (310175 -> 303733) while growing .aai/ROLE_COMMON.md (already inside TEST-010's extra accounting) by 3195 B (1666 -> 4861); without reconciliation headroom would jump 502 -> 3749, breaching HEADROOM_CAP=2048; this entry retires exactly 3247 B (6442 minus 3195) of credit so headroom lands back at 502 within the cap (per TEST-010's own remediation message: the corpus legitimately shrank below the credit, so LOWER JUSTIFIED_GROWTH_BYTES)"
  "282 CHANGE-0096-botfix SKILL_PR 5d bot-review hardening reword (P1: the empty-sweep stop now requires a bot-authored review to EXIST — zero bot activity is never a stop while the bounded window is open; poll-once wording replaced by re-poll-within-window) added 282 B of load-bearing gating prose beyond the prior +1147 credit; credited at the true +282 B growth, measured against TEST-010 floor deficit 282 B"
  "4774 implementation-mode-choice user-facing implementation-mode choice surfaced at end of intake + honored downstream (SPEC spec-implementation-mode-choice, ceremony_level 3): .aai/INTAKE_COMMON.md IMPLEMENTATION MODE CHOICE block (3-way choice full-TDD/direct+tests/direct-without-tests + signal-derived recommendation + set-strategy --source intake recording + back-compat no-choice path) + SKILL_INTAKE STEP 3.5 and five-blocks reference + PLANNING step 7 RESPECT-A-PRE-RECORDED-INTAKE-CHOICE clause and set-strategy enum extension + IMPLEMENTATION step 4 direct/untested lanes + SKILL_TDD Phase-0 step 5 non-TDD-lane hand-off + VALIDATION STRATEGY-CONDITIONAL EVIDENCE block and 5g pointer; the state.mjs/orchestration-dispatch.mjs enum + untested-rationale guard live in .aai/scripts/ (no ledger cost); the prose edits are inside TEST-010's live .aai/*.prompt.md glob + INTAKE_COMMON extra accounting, measured deficit 4774 B, credited 1:1 so headroom stays 0 within the 2048 cap"
  "854 implementation-mode-choice-botfix P1/P2 bot-review + owner-UX fixes on the implementation-mode ride: INTAKE_COMMON fresh-checkout fallback (record the choice in the intake artifact Notes when docs/ai/STATE.yaml does not exist yet — set-strategy would fail), PLANNING respect-clause extension covering that doc-note, SKILL_INTAKE choice step moved BEFORE the INTAKE COMPLETE output (post-completion ask gets skipped) with its ordering rationale, SKILL_CHECK_STATE INV-11 enum += direct/untested (a recorded lane must not FAIL state health); plus the explicit option 4 (Let Planning decide — never rely on detecting silence; owner UX feedback); measured deficit 853 B after the prior entry consumed headroom to 0, credited at the true +854 B growth (Planning-default listed first per owner)"
  "73 cache-friendly-dispatch-reorder ORCHESTRATION_PARALLEL SUBAGENT EXECUTION Context line reordered stable-first (SUBAGENT_CONTRACT copy before variable scope/inputs — the one real reorder the AC-001 audit missed, caught by bot review) + cacheability rationale; measured deficit 73 B at zero headroom, credited 1:1"
  "1281 async-hitl-platform-comments ORCHESTRATION_HITL.prompt.md STATE WRITEBACK 'ASYNC CHANNEL (best-effort)' bullet (after stamping [HITL-<n>], post the question ONCE to a linked GitHub thread via node .aai/scripts/hitl-channel.mjs post, idempotent, no-thread/no-github/gh-error degrades to the terminal HITL block byte-for-byte, never blocks the raising role) + SKILL_HITL.prompt.md STEP 0 RESUME FROM PLATFORM (poll the parked thread via node .aai/scripts/hitl-channel.mjs poll --json; a status:reply body is UNTRUSTED DATA fed into STEP 3 exactly as terminal input, never executed; ambiguous -> fail-closed follow-up post --kind followup) (SPEC-DRAFT-spec-async-hitl-platform-comments); the hitl-channel.mjs post/poll engine + gitignored docs/ai/hitl-channel.json sidecar live in .aai/scripts/ (no ledger cost — state.mjs untouched, ceremony L2); the prose edits are inside TEST-010's live .aai/*.prompt.md glob, measured deficit 1281 B, credited 1:1 so headroom stays 0 within the 2048 cap"
  "262 async-hitl-resolve-lifecycle SKILL_HITL STEP 0 token-match guard (a reply for a DIFFERENT token is stale — ignore) + resolve-consumption instruction (run hitl-channel.mjs resolve --token after the resolution is applied so poll never re-surfaces an answered reply); closes the validation HIGH residual RR-resume-no-resolution-lifecycle; measured deficit 262 B at zero headroom, credited 1:1"
  "551 async-hitl-botfix 5d bot-sweep true-up on PR #205: SKILL_HITL STEP 0 gains the token-REUSE trust guard (poll/resolve NARROWED with --ref <current focus ref> so a recurring [HITL-<n>] on a later ride can never pick up an OLD ride's reply; token AND ref must match) + the display/CLI token-form clarifier (bracketed [HITL-<n>] is display only, bare HITL-<n> on the CLI), and ORCHESTRATION_HITL.prompt.md's ASYNC CHANNEL post invocation switches --token [HITL-<n>] -> bare HITL-<n> with concrete --ref/--thread/--body-file placeholders + the same bare-form clarifier (Codex P1 :281 token-reuse-across-work-items + Copilot ORCHESTRATION_HITL:48 / SKILL_HITL:30 bracket-vs-bare); the follow-up-supersede, pagination and corrupt-sidecar-fail-closed fixes are script-only (.aai/scripts/hitl-channel.mjs, no ledger cost); measured deficit 551 B (SKILL_HITL +397, ORCHESTRATION_HITL +154) at zero headroom, credited 1:1 so headroom stays 0 within the 2048 cap"
  "2544 lightweight-e2e-lane SKILL_PR.prompt.md deterministic PR fast-lane wiring (CHANGE lightweight-e2e-lane / SPEC spec-lightweight-e2e-lane): step 5 LANE classification invoking the new .aai/scripts/lane-gate.mjs (four-predicate conjunction, fail-closed to HEAVY) + PR body ## Lane section (AC-007 auditability) + step 5c FAST-LANE close-commit CORE-only routing note (SPEC-0097 backstop preserved) + step 5d FAST-LANE optional-on-demand external sweep with the internal dual-verdict review kept mandatory as the compensating control (re-armable by any reviewer/bot); the lane-gate.mjs engine + tests live outside the .aai/*.prompt.md glob (no ledger cost — PROFILES core-classified), the prose edits are inside TEST-010's live glob, measured growth 2544 B (18275 -> 20819), credited 1:1 so headroom stays 0 within the 2048 cap"
  "349 lightweight-lane-botfix SKILL_PR LANE step RECOMPUTE-after-close-commit clause (bot-review P1: a lane computed once before step 5c could not govern the FINAL branch diff; the verdict now recomputes after any later commit and can only be lost by growth, never regained by trimming); measured deficit 349 B, credited 1:1"
  "196 runtime-state-consolidation SKILL_CODE_REVIEW.prompt.md Verdict 2 SIDECAR LIFECYCLE convention pin (a NEW gitignored runtime sidecar that hand-rolls load/write/stale/claim/GC instead of .aai/scripts/lib/runtime-file.mjs is a BLOCKING finding, reopens bug classes A-F) — the CONVENTION half (intake Stage 3) of the shared-sidecar-lib change; the runtime-file.mjs lib + its negative-control suite live in .aai/scripts/lib/ + tests/skills/ (no ledger cost — PROFILES core-classified, outside the .aai/*.prompt.md glob), and the hitl-channel.mjs migration is script-only; measured growth 196 B (10409 -> 10605), credited 1:1 so headroom stays 0 within the 2048 cap"
  "238 r-guard-runtime-enforcement ORCHESTRATION_PARALLEL.prompt.md SUBAGENT EXECUTION Env clause (R-GUARD Stage 1 / SPEC-0113): export AAI_ROLE=subagent in the spawned subagent's environment so its state.mjs STATE mutations refuse with exit 3, keep it UNSET for the orchestrator's own writes; the state.mjs guard clause + metrics-flush.mjs Stage-2/3 forensic checks live in .aai/scripts/ (no ledger cost), and the fuller ENV-row wiring + updated R-GUARD residual note land in .aai/SUBAGENT_PROTOCOL.md which sits OUTSIDE TEST-010's live .aai/*.prompt.md glob AND its extra accounting (INTAKE_COMMON/STATE_FALLBACK/ROLE_COMMON only) — the same out-of-glob treatment CHANGE-0061 subagent-protocol-slim applied, so it carries no measured deficit; the ONE in-glob edit is inside TEST-010's live glob, measured deficit 238 B at zero headroom, credited 1:1 so headroom stays 0 within the 2048 cap"
)
JUSTIFIED_ADDITIONS+=( "189 lane-intake-ceremony SKILL_PR --intake fallback doc for spec-less L0/L1 rides (measured deficit 189 B, 2026-08-02)" )
# DIET RIDE 2 2026-08-02 (CHANGE-DRAFT-prompt-diet-2-safe-wins): executed the
# zero-pin "safe immediate wins" rows of docs/analysis/unhobbling-audit.md
# (Phase 0 of CHANGE-0113). Measured shrink 12873 B across 5 files, live
# .aai/*.prompt.md glob 313505 -> 300632, NO new .aai/** file and NO growth in
# TEST-010's extra accounting (INTAKE_COMMON/STATE_FALLBACK/ROLE_COMMON
# untouched), so the whole 12873 B is genuine reduction:
#   SKILL_WORKTREE  -6019 (15245 -> 9226): git-tutorial intro, the drifted
#     inline STATE.yaml heredoc -> seed from .aai/templates/STATE_TEMPLATE.yaml,
#     Switch/List/Sync command sections -> their git one-liners, the two
#     invented-path walkthroughs, Best Practices -> pointer at PLANNING step 8,
#     the re-implemented git safety checks, Troubleshooting, METRICS example
#     and Example Session. Recommendation Gate, Setup recipe and the
#     archive-STATE-BEFORE-remove Cleanup ordering kept verbatim.
#   VALIDATION      -2098 (19220 -> 17122): RATIONALIZATION TABLE + 6 of 7
#     STRICT RULES (each already imperative in PROCESS 5a-5g / INVARIANT
#     RULES); the SUBAGENT_PROTOCOL merge line is pinned and stays.
#   SKILL_TDD       -1860 (17870 -> 16010): Phase 0 steps 1-4/7 -> pointer at
#     ORCHESTRATION.prompt.md + orchestration-dispatch.mjs (steps 5/6 verbatim
#     -- implementation-mode TEST-005 and ROLE_COMMON's "Phase 0 step 6"
#     reference pin them), the three phase checklists, Superpowers attribution.
#   PLANNING        -1699 (12772 -> 11073): RATIONALIZATION TABLE + 2 of 3
#     STRICT RULES (INVARIANT RULES L14/L16, step 10 freeze, HITL-1).
#   SKILL_LOOP      -1197 (24833 -> 23636): CHECKPOINT GATE literal terminal
#     templates -> the gate's rules (mode default is `none`; kept in-file
#     rather than the audit's new .aai/system/ file to avoid a PROFILES
#     companion obligation), 5 of 7 STRICT RULES.
# Per TEST-010's remediation rule the credit is LOWERED, not padded: without
# reconciliation headroom jumps 1530 -> 14403, breaching HEADROOM_CAP=2048.
# This entry retires exactly 12873 B so headroom lands back at 1530/2048 and
# the TEST-012 pin moves 1305 -> -11568.
JUSTIFIED_ADDITIONS+=( "-12873 prompt-diet-2-safe-wins RECLAIMED credit (NEGATIVE entry, CHANGE-DRAFT-prompt-diet-2-safe-wins): see the DIET RIDE 2 block above for the per-file breakdown and the surviving-home evidence; every deleted row was re-grepped against tests/**/*.sh, *.mjs and *.Tests.ps1 for pin coupling before the cut, and no pinned sentence was touched" )
JUSTIFIED_ADDITIONS+=( "216 CHANGE-0122-strategy-scaled-evidence PLANNING.prompt.md step 7 pointer (write the spec's AC/Verification demands from the recorded strategy's row in SPEC_TEMPLATE '### Evidence by strategy'; direct/untested owe NO stored RED artifact, spec-lint flags the mismatch at freeze) — the evidence TABLE itself lives in .aai/templates/SPEC_TEMPLATE.md, outside TEST-010's live .aai/*.prompt.md glob and its extra accounting, so it carries no ledger cost; measured growth 216 B (11073 -> 11289), credited 1:1 so headroom stays unchanged at 1150 within the 2048 cap" )
JUSTIFIED_ADDITIONS+=( "889 CHANGE-0120-cheap-ticks the three deterministic-tick wirings that let a mechanical tick stop respawning agents: ORCHESTRATION.prompt.md step 1 gains --confirm and step 3 gains the rule-9x advance_phase_to_implementation exception (+186 B, file HELD at exactly 40 lines — the historical SPEC-0017 cap, well under TEST-011's enforced 45), PLANNING.prompt.md step 10 routes freeze through the new atomic node .aai/scripts/spec-freeze.mjs instead of hand-writing either half (+237 B), ORCHESTRATION_PARALLEL.prompt.md IMPLEMENTATION STRATEGY AND ISOLATION gains the REVIEW-SCOPE EDITS ARE NOT A PLANNING DISPATCH pointer at node .aai/scripts/spec-scope-edit.mjs (+466 B); the three engines (orchestration-dispatch.mjs rule 9x, spec-scope-edit.mjs, spec-freeze.mjs), the docs-model.mjs content-hash helpers and the spec-lint half-frozen rule all live in .aai/scripts/ and carry NO ledger cost; measured deficit 889 B (headroom 1150 -> 261), credited 1:1 at the true growth so headroom returns to 1150 within the 2048 cap and the TEST-012 pin moves -11352 -> -10463" )
JUSTIFIED_ADDITIONS+=( "14 cheap-ticks-review set-phase flag form in ORCHESTRATION rule-9x exception (review BLOCKING 3; measured deficit 14 B, 2026-08-05)" )
JUSTIFIED_ADDITIONS+=( "492 test-registration-guard corpus-sweep VALIDATION rule + overpromising-test-name review pin (measured deficit 492 B, 2026-08-05)" )
# ALTITUDE ADOPTION 2026-08-06 (CHANGE-DRAFT-adopt-v2-planning, closing
# CHANGE-0113): .aai/PLANNING.prompt.md replaced by the experiment-winning V2
# ALTITUDE variant (docs/analysis/altitude-variants/V2-PLANNING.md) —
# 4 principles + one worked example + a "what already decides what" authority
# table, in place of 12 numbered steps restating what spec-lint / spec-freeze /
# state.mjs / the templates already enforce. Replay evidence:
# docs/analysis/altitude-replay.md (median Q 13 vs V0's 11, hallucinations
# -31%, D1/D3/D4 pass); D2 was satisfied first by the five behavioral probes
# (R04/R05/R09/R21/R31) shipped in the same ride.
#   MEASURED: 11526 -> 10227 B, a 1299 B reduction — NOT the variant's raw
#   -3685 B. The difference is deliberate and is the price of NOT turning an
#   adoption into a pin migration: V2's prose dropped the numbered spine, but
#   `^11) Emit the work-item brief` and `^12) Update docs/ai/STATE.yaml` are
#   pinned FOUR times each (ceremony x2, constitution, spec-lint) and the
#   hygiene ordering anchors need the literals `Set SPEC-FROZEN: true`,
#   `docs/ai/briefs/` and `Update docs/ai/STATE.yaml — PRIMARY PATH` in that
#   line order. Steps 10-12 therefore survive as V2's mechanical tail, carrying
#   the freeze/constitution/ceremony/brief/STATE literals verbatim; everything
#   above them is V2 text. Six suites stayed green with zero assertion edits.
#   No new .aai/** file, no growth in TEST-010's extra accounting.
# Per TEST-010's own remediation rule the credit is LOWERED, not padded:
# without reconciliation headroom jumps 1150 -> 2449, breaching
# HEADROOM_CAP=2048. This entry retires exactly 1299 B so headroom lands back
# at 1150/2048 and the TEST-012 pin moves -9957 -> -11256.
JUSTIFIED_ADDITIONS+=( "-1299 adopt-v2-planning RECLAIMED credit (NEGATIVE entry, CHANGE-0113 adoption): see the ALTITUDE ADOPTION block above for the variant, the replay evidence and the pin-reconciliation that explains why the measured shrink is 1299 B rather than the variant's raw 3685 B" )
JUSTIFIED_ADDITIONS+=( "2769 universal-routines new .aai/SKILL_ROUTINE.prompt.md thin wrapper documenting the on-demand /aai-routine standing-routine instantiation skill (CHANGE-0128-universal-routines / SPEC-0115-spec-universal-routines.md Spec-AC-06), mirroring SKILL_ISSUES.prompt.md's shape: run routine-emit.mjs, relay its output verbatim (incl. any MERGE DISABLED stderr line), walk the operator through the TEST AT CREATION fire; the routine-emit.mjs engine + .aai/routines/SCRYER.routine.md template live outside the .aai/*.prompt.md glob (no ledger cost); measured deficit 1619 B (headroom was -1619, below the required floor), credited at the MEASURED file size (`wc -c .aai/SKILL_ROUTINE.prompt.md` = 2769 B, not the 1619 B deficit — review-20260808T132824Z NB-4) so the credit is the true growth, not a rounded-to-the-floor number; headroom 1150 within the 2048 cap" )
JUSTIFIED_ADDITIONS+=( "466 validation-cost-calibration VALIDATION.prompt.md CEREMONY LANE block gains the blanket-full-suite-re-execution prohibition + adversarial-seam-probe obligation + close-before-CI rationale (Spec-AC-01), and the INDEPENDENCE REQUIREMENT block's 'cannot spawn a separate validator' clause gains a one-line pointer at .aai/SUBAGENT_PROTOCOL.md's four-tier isolation hierarchy (Spec-AC-03) — the ONLY in-glob edit in this scope, SUBAGENT_PROTOCOL.md itself sits outside TEST-010's live .aai/*.prompt.md glob and its extra accounting so its Spec-AC-02/03/04 edits carry no ledger cost; measured growth 466 B (17407 -> 17873), credited 1:1 so headroom stays unchanged at 1150 within the 2048 cap" )
JUSTIFIED_ADDITIONS+=( "163 validation-cost-calibration-review-remediation CHANGE-0132 code-review NB-1/CQ-7 carve-out sentence in VALIDATION.prompt.md's CEREMONY LANE lightweight-lane bullet (review-20260812T083704Z): 'A full-suite command DECLARED by the spec's own Test Plan is part of the declared scope and still runs; the prohibition targets an UNDECLARED blanket sweep.' -- reconciles the DECLARED-scope obligation with the no-blanket-re-run prohibition so a foreign LLM validator on a downstream project (where Test Plans routinely name whole suites) has a precedence rule instead of two contradictory instructions; the ONLY in-glob edit in this remediation batch, measured growth 163 B (17873 -> 18036), credited 1:1 so headroom stays unchanged at 1150 within the 2048 cap" )
JUSTIFIED_ADDITIONS+=( "432 bot-sweep-pr246-remediation PR #246 bot-sweep close: VALIDATION.prompt.md CEREMONY LANE lightweight-lane bullet's close-before-CI justification was imprecise (Codex P1) -- skill-suite.yml's selector runs only matched suites pre-merge on an ordinary mapped-path PR; the full-suite proof lands at merge-to-main or the nightly run, POST-merge, unless the PR carries the ci-full label or its diff trips a fail-open trigger. Reworded so lightweight-lane validation REQUIRES a pre-merge full-suite CI proof (label or fail-open path) and the validator's report must name which applies; SUBAGENT_PROTOCOL.md's tier-3 precondition fix (Codex P1, contradiction with tier 1's fork_turns_supported fallthrough) sits outside TEST-010's live .aai/*.prompt.md glob so it carries no ledger cost; the ONLY in-glob edit in this batch, measured growth 432 B (18036 -> 18468), credited 1:1 so headroom stays unchanged at 1150 within the 2048 cap" )
JUSTIFIED_ADDITIONS+=( "216 doctor-win-selftest-f8-remediation CHANGE-0135 validation finding F8: .aai/SKILL_DOCTOR.prompt.md still said 'The 13 health-check categories' and enumerated only CAT-01..13 after the engine grew to 16 (CAT-14 Windows Self-Test, CAT-15 Windows Environment, CAT-16 Agent CLI Probe added by this same scope); corrected the count and the category list to name all three; the ONLY in-glob edit, measured growth 216 B (3222 -> 3438), credited 1:1 so headroom stays unchanged at 1150 within the 2048 cap" )
JUSTIFIED_ADDITIONS+=( "66 update-doctor-field-report SKILL_UPDATE.prompt.md step 2 relay clause (CHANGE-0137 / spec-update-doctor-field-report Spec-AC-05): the agent surfaces the DOCTOR verdict (or DOCTOR-REPORT SKIP) line + report path in the short update report instead of dropping it under the 'surface only' list; the update-doctor-report.mjs engine and both postambles live outside the .aai/*.prompt.md glob (no ledger cost); the ONLY in-glob edit, measured growth 66 B (2949 -> 3015, wc -c), inside the spec's 120 B budget, credited 1:1 so headroom stays unchanged at 1150 within the 2048 cap" )
JUSTIFIED_ADDITIONS+=( "502 canonical-test-invocation CHANGE-0139 / spec-canonical-test-invocation contract echo: .aai/AGENTS.md gains the '### Canonical test invocation' subsection (both allowlist-prefix literals + repo-root rule + prohibition, measured +472 B, 19168 -> 19640 wc -c; AGENTS.md sits outside TEST-010's live .aai/*.prompt.md glob per the friction-shadow-capture-wiring precedent, so it is credited manually at the exact delta) + the six in-glob prompt invocation mentions gain the canonical 'bash ' prefix at +5 B each = +30 B measured (VALIDATION 18468->18473, SKILL_LOOP 23636->23641, SKILL_VERIFY 3579->3584, SKILL_TEST_SKILLS 2722->2727, SKILL_BOOTSTRAP 5109->5114, SKILL_DESLOP 2928->2933); DYNAMIC_SKILLS.md is system/ (not corpus, no ledger cost) and the contract BODY lives on non-ledgered surfaces (docs/TECHNOLOGY.md, TECHNOLOGY_TEMPLATE.md, USER_GUIDE, product doc, wrapper Usage headers); credited at the exact measured 502 B sum, headroom 1150 -> 1622 within the 2048 cap" )
JUSTIFIED_ADDITIONS+=( "598 reporting-docs-true-up CHANGE-0140 / spec-reporting-docs-true-up Spec-AC-05: .aai/SKILL_DASHBOARD.prompt.md stale 'Tokens are mostly null ... known gap' caveat replaced by the truthful note-parse description (usage_total_tokens=<N> parsed via the shared .aai/scripts/lib/usage-note.mjs grammar under the D3 precedence rule, marker reported only as a TOTAL, named no-data panel state) + two truthful troubleshooting rows replacing the stale 'Token numbers look wrong | Expected' row; the generator/template/product-doc/USER_GUIDE edits live outside the .aai/*.prompt.md glob (no ledger cost); the ONLY in-glob edit, measured growth 598 B (4157 -> 4755, wc -c), credited 1:1 so headroom stays unchanged at 1622 within the 2048 cap" )
JUSTIFIED_ADDITIONS+=( "200 followup-registry CHANGE-0142 / spec-followup-registry D7: .aai/SKILL_CODE_REVIEW.prompt.md 'WARNINGS POLICY WITH TEETH' clause (b) reworded from the abstract 'promoted to a docs/ai/decisions.jsonl entry (decision id + rationale)' -- which named a thing this repo had no shape for -- to the concrete typed follow_up plus the node .aai/scripts/follow-ups.mjs add invocation and the never-hand-write rationale (one malformed line fails routine-emit's authorization reader closed over the WHOLE ledger); no new prompt file and no new reading anywhere, this prompt is already loaded by the code-review role and by nothing else; the follow-ups.mjs engine, the generate-factory-report.mjs follow_ups block, the decisions.jsonl backfill and docs/product/aai-decisions.md all live outside the .aai/*.prompt.md glob (no ledger cost); the ONLY in-glob edit, measured growth 200 B (10812 -> 11012, wc -c), exactly the spec D7 budget ceiling, credited 1:1 so headroom stays unchanged at 1622 within the 2048 cap and the TEST-012 pin moves -6044 -> -5844" )
JUSTIFIED_GROWTH_BYTES=0
for _entry in "${JUSTIFIED_ADDITIONS[@]}"; do
  JUSTIFIED_GROWTH_BYTES=$(( JUSTIFIED_GROWTH_BYTES + ${_entry%% *} ))
done
unset _entry   # do not leak the loop scratch var into the sourcing shell
# Anti-bloat guard (TEST-002/Spec-AC-02): headroom must stay in
# [0, HEADROOM_CAP] so the credit cannot be padded arbitrarily and future
# UNJUSTIFIED prompt growth beyond the cap still fails this test (forcing a
# new itemized ledger line, or a shrink, instead of a silent absorption).
HEADROOM_CAP=2048

# Pure helpers factored out of TEST-010 (Spec-AC-02/SPEC-0059) so synthetic
# fixtures can drive them with SYNTHETIC inputs, proving the breach-deficit
# template and the cap-bite guard WITHOUT mutating the real
# JUSTIFIED_ADDITIONS ledger or reading the live corpus.

# compute_reduction_headroom <baseline> <after> <extra> <credit> <required>
# Mirrors TEST-010's exact formula; echoes "<reduction> <headroom>".
compute_reduction_headroom() {
  local baseline=$1 after=$2 extra=$3 credit=$4 required=$5
  local reduction=$(( baseline - after - extra + credit ))
  local headroom=$(( reduction - required ))
  echo "$reduction $headroom"
}

# justified_growth_breach_suggestion <reduction> <required>
# Computes the exact deficit and echoes a ready-to-paste ledger-entry line.
justified_growth_breach_suggestion() {
  local reduction=$1 required=$2
  local deficit=$(( required - reduction ))
  echo "JUSTIFIED_ADDITIONS+=( \"$deficit <REF-ID> <rationale>\" )"
}
